/* Copyright (c) 2023 Otto Link. Distributed under the terms of the GNU General
 * Public License. The full license is in the file LICENSE, distributed with
 * this software. */
#include <stdexcept>

#include "hesiod/logger.hpp"
#include "hesiod/model/nodes/node_factory.hpp"

namespace hesiod
{

// HELPER
constexpr unsigned int str2int(const char *str, int h = 0)
{
  // https://stackoverflow.com/questions/16388510
  return !str[h] ? 5381 : (str2int(str, h + 1) * 33) ^ str[h];
}

std::map<std::string, std::string> get_node_inventory()
{
  std::map<std::string, std::string> node_inventory = {
      {"Abs", "Math/Base"},
      {"AbsSmooth", "Math/Base"},
      {"AccumulationCurvature", "Features/Landform"},
      {"Blend", "Operator/Blend"},
      {"Brush", "Primitive/Authoring"},
      {"Bump", "Primitive/Function"},
      {"Caldera", "Primitive/Geological"},
      {"Clamp", "Filter/Range"},
      {"Closing", "Operator/Morphology"},
      {"Cloud", "Geometry/Cloud"},
      {"CloudMerge", "Geometry/Cloud"},
      {"CloudLattice", "Geometry/Cloud"},
      {"CloudRandom", "Geometry/Cloud"},
      {"CloudRemapValues", "Geometry/Cloud"},
      {"CloudSDF", "Geometry/Cloud"},
      {"CloudToArrayInterp", "Geometry/Cloud"},
      {"CloudToPath", "Geometry/Cloud"},
      {"ColorizeCmap", "Texture"},
      {"ColorizeGradient", "Texture"},
      {"ColorizeSolid", "Texture"},
      {"CombineMask", "Mask"},
      {"ConvolveSVD", "Math/Convolution"},
      {"Cos", "Math/Base"},
      {"Crater", "Primitive/Geological"},
      {"Dendry", "Primitive/Coherent"},
      {"DepressionFilling", "Erosion"},
      {"Detrend", "Filter/Recurve"},
      {"DiffusionLimitedAggregation", "Primitive/Coherent"},
      {"Dilation", "Operator/Morphology"},
      {"DistanceTransform", "Operator/Morphology"},
      {"Erosion", "Operator/Morphology"},
      {"ExpandShrink", "Filter/Recast"},
      {"ExportAsset", "IO/Files"},
      {"ExportCloud", "IO/Files"},
      {"ExportHeightmap", "IO/Files"},
      {"ExportNormalMap", "IO/Files"},
      {"ExportPath", "IO/Files"},
      {"ExportTexture", "IO/Files"},
      {"Falloff", "Math/Boundaries"},
      {"FillTalus", "Operator/Transform"},
      {"Fold", "Filter/Recast"},
      {"Gain", "Filter/Recurve"},
      {"GammaCorrection", "Filter/Recurve"},
      {"GammaCorrectionLocal", "Filter/Recurve"},
      {"GaussianDecay", "Math/Base"},
      {"GaussianPulse", "Primitive/Function"},
      {"Gradient", "Math/Gradient"},
      {"GradientAngle", "Math/Gradient"},
      {"GradientNorm", "Math/Gradient"},
      {"GradientTalus", "Math/Gradient"},
      {"HeightmapToKernel", "Converter"},
      {"HeightmapToMask", "Converter"},
      {"HeightmapToRGBA", "Converter"},
      {"HydraulicBlur", "Erosion/Hydraulic"},
      {"HydraulicParticle", "Erosion/Hydraulic"},
      {"HydraulicProcedural", "Erosion/Hydraulic"},
      {"HydraulicRidge", "Erosion/Hydraulic"},
      {"HydraulicSchott", "Erosion/Hydraulic"},
      {"HydraulicStream", "Erosion/Hydraulic"},
      {"HydraulicStreamUpscaleAmplification", "Erosion/Hydraulic"},
      {"HydraulicVpipes", "Erosion/Hydraulic"},
      {"ImportHeightmap", "IO/Files"},
      {"ImportTexture", "IO/Files"},
      {"Inverse", "Math/Base"},
      {"KernelGabor", "Primitive/Kernel"},
      {"KernelPrim", "Primitive/Kernel"},
      {"KmeansClustering2", "Features/Clustering"},
      {"KmeansClustering3", "Features/Clustering"},
      {"Kuwahara", "Filter/Smoothing"},
      {"Laplace", "Filter/Smoothing"},
      {"Lerp", "Math/Base"},
      {"MakeBinary", "Operator/Morphology"},
      {"MakePeriodic", "Operator/Tiling"},
      {"MakePeriodicStitching", "Operator/Tiling"},
      {"Median3x3", "Filter/Smoothing"},
      {"MixNormalMap", "Texture"},
      {"MixTexture", "Texture"},
      {"Mixer", "Operator/Blend"},
      {"MorphologicalGradient", "Operator/Morphology"},
      {"Noise", "Primitive/Coherent"},
      {"NoiseFbm", "Primitive/Coherent"},
      {"NoiseIq", "Primitive/Coherent"},
      {"NoiseJordan", "Primitive/Coherent"},
      {"NoiseParberry", "Primitive/Coherent"},
      {"NoisePingpong", "Primitive/Coherent"},
      {"NoiseRidged", "Primitive/Coherent"},
      {"NoiseSwiss", "Primitive/Coherent"},
      {"NormalDisplacement", "Filter/Recast"},
      {"Opening", "Operator/Morphology"},
      {"Paraboloid", "Primitive/Function"},
      {"Path", "Geometry/Path"},
      {"PathBezier", "Geometry/Path"},
      {"PathBezierRound", "Geometry/Path"},
      {"PathBspline", "Geometry/Path"},
      {"PathDecasteljau", "Geometry/Path"},
      {"PathDig", "Geometry/Path"},
      {"PathFind", "Geometry/Path"},
      {"PathFractalize", "Geometry/Path"},
      {"PathMeanderize", "Geometry/Path"},
      {"PathResample", "Geometry/Path"},
      {"PathSDF", "Geometry/Path"},
      {"PathSmooth", "Geometry/Path"},
      {"PathToCloud", "Converter"},
      {"PathToHeightmap", "Converter"},
      {"Plateau", "Filter/Recurve"},
      {"Preview", "Debug"},
      {"QuiltingBlend", "Operator/Resynthesis"},
      {"QuiltingExpand", "Operator/Resynthesis"},
      {"QuiltingShuffle", "Operator/Resynthesis"},
      {"RadialDisplacementToXy", "Math"},
      {"RecastCanyon", "Filter/Recast"},
      {"RecastCliff", "Filter/Recast"},
      {"RecastCliffDirectional", "Filter/Recast"},
      {"RecastSag", "Filter/Recast"},
      {"Recurve", "Filter/Recurve"},
      {"RecurveKura", "Filter/Recurve"},
      {"RecurveS", "Filter/Recurve"},
      {"RelativeElevation", "Features/Landform"},
      {"Remap", "Filter/Range"},
      {"Rescale", "Filter/Range"},
      {"Reverse", "Math/Base"},
      {"ReverseMidpoint", "Primitive/Authoring"},
      {"Ridgelines", "Primitive/Authoring"},
      {"Rift", "Primitive/Function"},
      {"Rugosity", "Features"},
      {"Saturate", "Filter/Recurve"},
      {"ScanMask", "Mask"},
      {"SedimentDeposition", "Erosion/Deposition"},
      {"SelectAngle", "Mask/Selector"},
      {"SelectBlobLog", "Mask/Selector"},
      {"SelectCavities", "Mask/Selector"},
      {"SelectGt", "Mask/Selector"},
      {"SelectInterval", "Mask/Selector"},
      {"SelectInwardOutward", "Mask/Selector"},
      {"SelectMidrange", "Mask/Selector"},
      {"SelectMultiband3", "Mask/Selector"},
      {"SelectPulse", "Mask/Selector"},
      {"SelectRivers", "Mask/Selector"},
      {"SelectSlope", "Mask/Selector"},
      {"SelectTransitions", "Mask/Selector"},
      {"SelectValley", "Mask/Selector"},
      {"SetAlpha", "Texture"},
      {"ShapeIndex", "Filter/Smoothing"},
      {"SharpenCone", "Filter/Smoothing"},
      {"ShiftElevation", "Filter/Range"},
      {"Slope", "Primitive/Function"},
      {"SmoothCpulse", "Filter/Smoothing"},
      {"SmoothFill", "Filter/Smoothing"},
      {"SmoothFillHoles", "Filter/Smoothing"},
      {"SmoothFillSmearPeaks", "Filter/Smoothing"},
      {"Smoothstep3", "Math/Base"},
      {"Smoothstep5", "Math/Base"},
      {"Stamping", "Primitive/Coherent"},
      {"SteepenConvective", "Filter/Recast"},
      {"Step", "Primitive/Function"},
      {"Stratify", "Erosion/Stratify"},
      {"StratifyOblique", "Erosion/Stratify"},
      {"StratifyMultiscale", "Erosion/Stratify"},
      {"Terrace", "Filter/Recurve"},
      {"TextureQuiltingExpand", "Operator/Resynthesis"},
      {"TextureQuiltingShuffle", "Operator/Resynthesis"},
      {"Thermal", "Erosion/Thermal"},
      {"ThermalAutoBedrock", "Erosion/Thermal"},
      {"ThermalRib", "Erosion/Thermal"},
      {"ThermalSchott", "Erosion/Thermal"},
      {"Translate", "Operator/Transform"},
      {"Unsphericity", "Features/Landform"},
      {"ValleyWidth", "Features/Landform"},
      {"Warp", "Operator/Transform"},
      {"WarpDownslope", "Operator/Transform"},
      {"WaveDune", "Primitive/Function"},
      {"WaveSine", "Primitive/Function"},
      {"WaveSquare", "Primitive/Function"},
      {"WaveTriangular", "Primitive/Function"},
      {"White", "Primitive/Random"},
      {"WhiteDensityMap", "Primitive/Random"},
      {"WhiteSparse", "Primitive/Random"},
      {"Wrinkle", "Filter/Recast"},
      {"ZeroedEdges", "Primitive/Random"},
      {"Zoom", "Operator/Transform"},
  };

  return node_inventory;
} // namespace hesiod

std::shared_ptr<gnode::Node> node_factory(const std::string           &node_type,
                                          std::shared_ptr<ModelConfig> config)
{
  auto sptr = std::make_shared<hesiod::BaseNode>(node_type, config);

  switch (str2int(node_type.c_str()))
  {
    SETUP_NODE(Abs, abs);
    SETUP_NODE(AbsSmooth, abs_smooth);
    SETUP_NODE(AccumulationCurvature, accumulation_curvature);
    SETUP_NODE(Blend, blend);
    SETUP_NODE(Brush, brush);
    SETUP_NODE(Bump, bump);
    SETUP_NODE(Caldera, caldera);
    SETUP_NODE(Clamp, clamp);
    SETUP_NODE(Closing, closing);
    SETUP_NODE(Cloud, cloud);
    SETUP_NODE(CloudMerge, cloud_merge);
    SETUP_NODE(CloudLattice, cloud_lattice);
    SETUP_NODE(CloudRandom, cloud_random);
    SETUP_NODE(CloudRemapValues, cloud_remap_values);
    SETUP_NODE(CloudSDF, cloud_sdf);
    SETUP_NODE(CloudToArrayInterp, cloud_to_array_interp);
    SETUP_NODE(CloudToPath, cloud_to_path);
    SETUP_NODE(ColorizeCmap, colorize_cmap);
    SETUP_NODE(ColorizeGradient, colorize_gradient);
    SETUP_NODE(ColorizeSolid, colorize_solid);
    SETUP_NODE(CombineMask, combine_mask);
    SETUP_NODE(Cos, cos);
    SETUP_NODE(ConvolveSVD, convolve_svd);
    SETUP_NODE(Crater, crater);
    SETUP_NODE(Dendry, dendry);
    SETUP_NODE(DepressionFilling, depression_filling);
    SETUP_NODE(Detrend, detrend);
    SETUP_NODE(DiffusionLimitedAggregation, diffusion_limited_aggregation);
    SETUP_NODE(Dilation, dilation);
    SETUP_NODE(DistanceTransform, distance_transform);
    SETUP_NODE(Erosion, erosion);
    SETUP_NODE(ExpandShrink, expand_shrink);
    SETUP_NODE(ExportAsset, export_asset);
    SETUP_NODE(ExportCloud, export_cloud);
    SETUP_NODE(ExportHeightmap, export_heightmap);
    SETUP_NODE(ExportNormalMap, export_normal_map);
    SETUP_NODE(ExportPath, export_path);
    SETUP_NODE(ExportTexture, export_texture);
    SETUP_NODE(Falloff, falloff);
    SETUP_NODE(FillTalus, fill_talus);
    SETUP_NODE(Fold, fold);
    SETUP_NODE(Gain, gain);
    SETUP_NODE(GammaCorrection, gamma_correction);
    SETUP_NODE(GammaCorrectionLocal, gamma_correction_local);
    SETUP_NODE(GaussianDecay, gaussian_decay);
    SETUP_NODE(GaussianPulse, gaussian_pulse);
    SETUP_NODE(Gradient, gradient);
    SETUP_NODE(GradientAngle, gradient_angle);
    SETUP_NODE(GradientNorm, gradient_norm);
    SETUP_NODE(GradientTalus, gradient_talus);
    SETUP_NODE(HeightmapToKernel, heightmap_to_kernel);
    SETUP_NODE(HeightmapToMask, heightmap_to_mask);
    SETUP_NODE(HeightmapToRGBA, heightmap_to_rgba);
    SETUP_NODE(HydraulicBlur, hydraulic_blur);
    SETUP_NODE(HydraulicParticle, hydraulic_particle);
    SETUP_NODE(HydraulicProcedural, hydraulic_procedural);
    SETUP_NODE(HydraulicRidge, hydraulic_ridge);
    SETUP_NODE(HydraulicSchott, hydraulic_schott);
    SETUP_NODE(HydraulicStream, hydraulic_stream);
    SETUP_NODE(HydraulicStreamUpscaleAmplification,
               hydraulic_stream_upscale_amplification);
    SETUP_NODE(HydraulicVpipes, hydraulic_vpipes);
    SETUP_NODE(ImportHeightmap, import_heightmap);
    SETUP_NODE(ImportTexture, import_texture);
    SETUP_NODE(Inverse, inverse);
    SETUP_NODE(KernelGabor, kernel_gabor);
    SETUP_NODE(KernelPrim, kernel_prim);
    SETUP_NODE(KmeansClustering2, kmeans_clustering2);
    SETUP_NODE(KmeansClustering3, kmeans_clustering3);
    SETUP_NODE(Kuwahara, kuwahara);
    SETUP_NODE(Laplace, laplace);
    SETUP_NODE(Lerp, lerp);
    SETUP_NODE(MakeBinary, make_binary);
    SETUP_NODE(MakePeriodic, make_periodic);
    SETUP_NODE(MakePeriodicStitching, make_periodic_stitching);
    SETUP_NODE(Median3x3, median3x3);
    SETUP_NODE(Mixer, mixer);
    SETUP_NODE(MixNormalMap, mix_normal_map);
    SETUP_NODE(MixTexture, mix_texture);
    SETUP_NODE(MorphologicalGradient, morphological_gradient);
    SETUP_NODE(Noise, noise);
    SETUP_NODE(NoiseFbm, noise_fbm);
    SETUP_NODE(NoiseIq, noise_iq);
    SETUP_NODE(NoiseJordan, noise_iq);
    SETUP_NODE(NoiseParberry, noise_parberry);
    SETUP_NODE(NoisePingpong, noise_pingpong);
    SETUP_NODE(NoiseRidged, noise_ridged);
    SETUP_NODE(NoiseSwiss, noise_swiss);
    SETUP_NODE(NormalDisplacement, normal_displacement);
    SETUP_NODE(Opening, opening);
    SETUP_NODE(Paraboloid, paraboloid);
    SETUP_NODE(Path, path);
    SETUP_NODE(PathBezier, path_bezier);
    SETUP_NODE(PathBezierRound, path_bezier_round);
    SETUP_NODE(PathBspline, path_bspline);
    SETUP_NODE(PathDecasteljau, path_decasteljau);
    SETUP_NODE(PathDig, path_dig);
    SETUP_NODE(PathFind, path_find);
    SETUP_NODE(PathFractalize, path_fractalize);
    SETUP_NODE(PathMeanderize, path_meanderize);
    SETUP_NODE(PathResample, path_resample);
    SETUP_NODE(PathSDF, path_sdf);
    SETUP_NODE(PathSmooth, path_smooth);
    SETUP_NODE(PathToCloud, path_to_cloud);
    SETUP_NODE(PathToHeightmap, path_to_heightmap);
    SETUP_NODE(Plateau, plateau);
    SETUP_NODE(Preview, preview);
    SETUP_NODE(QuiltingBlend, quilting_blend);
    SETUP_NODE(QuiltingExpand, quilting_expand);
    SETUP_NODE(QuiltingShuffle, quilting_shuffle);
    SETUP_NODE(RadialDisplacementToXy, radial_displacement_to_xy);
    SETUP_NODE(RecastCanyon, recast_canyon);
    SETUP_NODE(RecastCliff, recast_cliff);
    SETUP_NODE(RecastCliffDirectional, recast_cliff_directional);
    SETUP_NODE(RecastSag, recast_sag);
    SETUP_NODE(Recurve, recurve);
    SETUP_NODE(RecurveKura, recurve_kura);
    SETUP_NODE(RecurveS, recurve_s);
    SETUP_NODE(RelativeElevation, relative_elevation);
    SETUP_NODE(Remap, remap);
    SETUP_NODE(Rescale, rescale);
    SETUP_NODE(Reverse, reverse);
    SETUP_NODE(ReverseMidpoint, reverse_midpoint);
    SETUP_NODE(Ridgelines, ridgelines);
    SETUP_NODE(Rift, rift);
    SETUP_NODE(Rugosity, rugosity);
    SETUP_NODE(Saturate, saturate);
    SETUP_NODE(ScanMask, scan_mask);
    SETUP_NODE(SedimentDeposition, sediment_deposition);
    SETUP_NODE(SelectAngle, select_angle);
    SETUP_NODE(SelectBlobLog, select_blob_log);
    SETUP_NODE(SelectCavities, select_cavities);
    SETUP_NODE(SelectGt, select_gt);
    SETUP_NODE(SelectInterval, select_interval);
    SETUP_NODE(SelectInwardOutward, select_inward_outward);
    SETUP_NODE(SelectMultiband3, select_multiband3);
    SETUP_NODE(SelectMidrange, select_midrange);
    SETUP_NODE(SelectPulse, select_pulse);
    SETUP_NODE(SelectRivers, select_rivers);
    SETUP_NODE(SelectSlope, select_slope);
    SETUP_NODE(SelectTransitions, select_transitions);
    SETUP_NODE(SelectValley, select_valley);
    SETUP_NODE(SetAlpha, set_alpha);
    SETUP_NODE(ShapeIndex, shape_index);
    SETUP_NODE(SharpenCone, sharpen_cone);
    SETUP_NODE(ShiftElevation, shift_elevation);
    SETUP_NODE(Slope, slope);
    SETUP_NODE(SmoothCpulse, smooth_cpulse);
    SETUP_NODE(SmoothFill, smooth_fill);
    SETUP_NODE(SmoothFillHoles, smooth_fill_holes);
    SETUP_NODE(SmoothFillSmearPeaks, smooth_fill_smear_peaks);
    SETUP_NODE(Smoothstep3, smoothstep3);
    SETUP_NODE(Smoothstep5, smoothstep5);
    SETUP_NODE(Stamping, stamping);
    SETUP_NODE(SteepenConvective, steepen_convective);
    SETUP_NODE(Step, step);
    SETUP_NODE(Stratify, stratify);
    SETUP_NODE(StratifyOblique, stratify_oblique);
    SETUP_NODE(StratifyMultiscale, stratify_multiscale);
    SETUP_NODE(Terrace, terrace);
    SETUP_NODE(TextureQuiltingExpand, texture_quilting_expand);
    SETUP_NODE(TextureQuiltingShuffle, texture_quilting_shuffle);
    SETUP_NODE(Translate, translate);
    SETUP_NODE(Thermal, thermal);
    SETUP_NODE(ThermalAutoBedrock, thermal_auto_bedrock);
    SETUP_NODE(ThermalRib, thermal_rib);
    SETUP_NODE(ThermalSchott, thermal_schott);
    SETUP_NODE(Unsphericity, unsphericity);
    SETUP_NODE(ValleyWidth, valley_width);
    SETUP_NODE(Warp, warp);
    SETUP_NODE(WarpDownslope, warp_downslope);
    SETUP_NODE(WaveDune, wave_dune);
    SETUP_NODE(WaveSine, wave_sine);
    SETUP_NODE(WaveSquare, wave_square);
    SETUP_NODE(WaveTriangular, wave_triangular);
    SETUP_NODE(White, white);
    SETUP_NODE(WhiteDensityMap, white_density_map);
    SETUP_NODE(WhiteSparse, white_sparse);
    SETUP_NODE(Wrinkle, wrinkle);
    SETUP_NODE(ZeroedEdges, zeroed_edges);
    SETUP_NODE(Zoom, zoom);
  default:
    throw std::invalid_argument("Unknown node type in node_factory: " + node_type);
  }

  return sptr;
}

} // namespace hesiod
